# Пермишены:
# axocode.reload - Перезагрузка плагина.
# axocode.stat - Просмотр статистики промокода.
# axocode.code - использование кодов (любых)

Settings:
  Chat: "Я люблю этот сервер" # Что нужно написать, чтоб использовать код
  Walk: 1000 # Сколько блоков надо пройти, только int !
  Timed: 18000 # Сколько надо наиграть, в секундах!

codes:
  somecode: #Без пробелов!
    commands:
      - "/gmc {player}"
    date: -1
  code:
    commands:
      - "/give {player} DIAMOND 1"
      - "/spawn {player}"
    date: 9999999999 # До какого времени можно использовать. UNIX формат. Если бесконечно укажите -1. Unix конвертер: https://time.is/ru/Unix_time_converter

Messages:
  code-usage: "Использование: /code <код>"
  stat-usage: "Использование: /axocode stat <код>"

  already: "Вы уже использовали {code}!"
  use: "Вы активировали промокод!"
  only-player: "Только для игрока!"
  not-found: "Промокод {code} не найден!"
  stat: "У кода '{code}' {usages} активаций."
  not: "нет" # Относится к stat
  reload: "Плагин AxoCodes перезагружен."
  perm: "Недостаточно прав!"

  no-chat: "Вы не можете активировать промокод, вы не написали в чат \"Я люблю этот сервер\""
  no-walk: "Вы не можете активировать промокод, вы не пробежали 1.000 блоков."
  no-time: "Вы не можете активировать промокод, вы не отыграли 5 часов."